// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKeIYEoSvyyDzRfEH87qfKLY4nCCDKvHQ',
    appId: '1:738069288635:web:168ed2511b3097fdd43b9e',
    messagingSenderId: '738069288635',
    projectId: 'hepato-diagnosis-f40a6',
    authDomain: 'hepato-diagnosis-f40a6.firebaseapp.com',
    storageBucket: 'hepato-diagnosis-f40a6.firebasestorage.app',
    measurementId: 'G-5JH4L913K1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcES81jInaTWmblCCbqVM3QxDVfCW1ddM',
    appId: '1:738069288635:android:349afea4991b8a8bd43b9e',
    messagingSenderId: '738069288635',
    projectId: 'hepato-diagnosis-f40a6',
    storageBucket: 'hepato-diagnosis-f40a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjfW-Cy8HafmQ3pMl8-J1-l9E3QeO8fPM',
    appId: '1:738069288635:ios:d5a1ac2657f94b9cd43b9e',
    messagingSenderId: '738069288635',
    projectId: 'hepato-diagnosis-f40a6',
    storageBucket: 'hepato-diagnosis-f40a6.firebasestorage.app',
    iosBundleId: 'com.example.hepato',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjfW-Cy8HafmQ3pMl8-J1-l9E3QeO8fPM',
    appId: '1:738069288635:ios:d5a1ac2657f94b9cd43b9e',
    messagingSenderId: '738069288635',
    projectId: 'hepato-diagnosis-f40a6',
    storageBucket: 'hepato-diagnosis-f40a6.firebasestorage.app',
    iosBundleId: 'com.example.hepato',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKeIYEoSvyyDzRfEH87qfKLY4nCCDKvHQ',
    appId: '1:738069288635:web:834de8d8687427a3d43b9e',
    messagingSenderId: '738069288635',
    projectId: 'hepato-diagnosis-f40a6',
    authDomain: 'hepato-diagnosis-f40a6.firebaseapp.com',
    storageBucket: 'hepato-diagnosis-f40a6.firebasestorage.app',
    measurementId: 'G-LDM650WZND',
  );
}
